redis:
    host: localhost
    port: 6379
    dbIndex: 0
    password: r3d1sp4s$
datasource:
    url: "postgres://omni-customer:omnicustomerpass@localhost:5432/omni-customer"
application:
    port: ":8080"
cache:
    expireactivation: 3600
jwt:
    expiration: 720
    refreshexpiration: 10800
    secret: "Aval4nch3X8_a!324$"
    refreshsecret: "TuRb0$_p!934#"
api:
  micro:
    path: '/api/customer'
  key:
    internal: "60d6ac10-6445-42ba-b916-8dfd43e81e46"