package utility

const ERR_MSG_SOMETHING_WENT_WRONG = "Something went wrong"
const ERR_MSG_DATA_NOT_FOUND = "Data not found"
const ERR_MSG_UNAUTHORIZED = "Unauthorized access"
const SUCCESS_MSG_DATA_SUBMIT = "Data submitted successfuly"
const SUCCESS_MSG_DATA_FOUND = "Here is your data"
const CUSTOMER_STATUS_REGISTERED = 0
const CUSTOMER_STATUS_ACTIVATED = 1
const CUSTOMER_STATUS_BLOCKED = 2
const CUSTOMER_STATUS_SUSPENDED = 3
const CACHE_CUSTOMER_ACTIVATION = "CUSTOMERACTIVATION:"
const CACHE_CUSTOMER_ACTIVATION_EMAIL = "CUSTOMERACTIVATIONEMAIL:"
const CACHE_CUSTOMER_LOGIN = "CUSTOMERLOGIN:"
